services:
  web:
    # 'build: .' 대신 아래 'image:'를 사용합니다.
    image: sebinbaek0918/pixpl-web:latest
    volumes:
      - static_volume:/app/static
    expose:
      - "8000"

  nginx:
    # 'build: ./nginx' 대신 아래 'image:'를 사용합니다.
    image: sebinbaek0918/pixpl-nginx:latest
    volumes:
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
