# Generated by Django 5.2.5 on 2025-08-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prompt",
            name="uploaded_image",
        ),
    ]
