# Generated by Django 5.2.5 on 2025-08-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_generatedimage_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='user',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='user',
            new_name='uuid',
        ),
    ]
