# Generated by Django 5.2.5 on 2025-08-25 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('business_type', models.CharField(max_length=30)),
                ('user_tag', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.generatedimage')),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.prompt')),
                ('uploaded_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.uploadedimage')),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='feed.feed')),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'unique_together': {('feed', 'user_uuid')},
            },
        ),
    ]
