# Generated by Django 5.2.5 on 2025-08-22 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
        ("studio", "0002_remove_prompt_uploaded_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="generated_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="studio.generatedimage",
                unique=True,
            ),
        ),
    ]
