# Generated by Django 5.2.5 on 2025-08-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=50, unique=True)),
                (
                    "business_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("is_profile_public", models.BooleanField(default=True)),
                ("received_picks", models.PositiveIntegerField(default=0)),
                ("gave_picks", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
